### ISSUE TITLE
Auto-reverting buffer makes current buffer dim

### ISSUE THREAD

**Issue by titibandit** [mina86/auto-dim-other-buffers.el#26] opened 2021-02-10 15:52 UTC
Hey,
When I have another buffer opened in an another window, with auto-revert-mode activated, and whenever this buffer auto-revert itself, it will dim the current window I'm in.
I don't know how auto-revert-mode functions, but it might be so that the buffers become active for a split second, making our current buffer dim. But then, it unfortunately stays so. 

It's happening having an auto-reverting buffer that is a PDF viewed using pdf-tools.

And the buffer somehow seems to stay the active one. I can tell because of the modeline that keeps its activated font. Just auto-dim dims it!
I'm not sure how I could debug this.
Thanks!

**Comment by mina86** [comment] 2021-02-10 16:48
I’m unable to reproduce it. Could you share your adob configuration? I.e. `M-x customize-group RET auto-dim-other-buffers RET` and copy changed values? Contents of `M-x report-emacs-bug RET` might also be useful.

**Comment by titibandit** [comment] 2021-02-10 16:56
That's what `report-emacs-bug` returns:
```
In GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
 of 2020-08-28 built on juergen
Windowing system distributor 'The X.Org Foundation', version 11.0.12010000
System Description: Arch Linux

Recent messages:
Wrote /home/thibaut/IENT/Themen/BA-1/thema.tex
Processing LaTeX file thema.tex...
PDF file produced.
Tangled 0 code blocks from thema.org
Reverting buffer ‘thema.pdf’.
Creating customization items...
Creating group...
Creating group entries...done
Creating customization items ...done
Creating customization setup...done

Configured using:
 'configure --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib
 --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int
 --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64
 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2
 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now'

Configured features:
XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY
INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB
TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON
PDUMPER LCMS2 GMP

Important settings:
  value of $LC_MONETARY: fr_FR.utf8
  value of $LC_NUMERIC: fr_FR.utf8
  value of $LC_TIME: fr_FR.utf8
  value of $LANG: en_US.UTF-8
  locale-coding-system: utf-8-unix

Major mode: Org

Minor modes in effect:
  shell-dirtrack-mode: t
  org-indent-mode: t
  org-superstar-mode: t
  auto-dim-other-buffers-mode: t
  global-hl-line-mode: t
  show-paren-mode: t
  global-display-line-numbers-mode: t
  display-line-numbers-mode: t
  persp-mode: t
  counsel-projectile-mode: t
  projectile-mode: t
  which-key-mode: t
  amx-mode: t
  ivy-rich-mode: t
  counsel-mode: t
  ivy-mode: t
  override-global-mode: t
  straight-use-package-mode: t
  straight-package-neutering-mode: t
  global-eldoc-mode: t
  electric-indent-mode: t
  mouse-wheel-mode: t
  file-name-shadow-mode: t
  global-font-lock-mode: t
  font-lock-mode: t
  blink-cursor-mode: t
  auto-composition-mode: t
  auto-encryption-mode: t
  auto-compression-mode: t
  column-number-mode: t
  line-number-mode: t
  visual-line-mode: t
  transient-mark-mode: t

Load-path shadows:
/home/thibaut/.emacs.d/straight/build/org/ob-asymptote hides /usr/share/emacs/27.1/lisp/org/ob-asymptote
/home/thibaut/.emacs.d/straight/build/org/ob-python hides /usr/share/emacs/27.1/lisp/org/ob-python
/home/thibaut/.emacs.d/straight/build/org/org-protocol hides /usr/share/emacs/27.1/lisp/org/org-protocol
/home/thibaut/.emacs.d/straight/build/org/org-archive hides /usr/share/emacs/27.1/lisp/org/org-archive
/home/thibaut/.emacs.d/straight/build/org/ob-stan hides /usr/share/emacs/27.1/lisp/org/ob-stan
/home/thibaut/.emacs.d/straight/build/org/org-duration hides /usr/share/emacs/27.1/lisp/org/org-duration
/home/thibaut/.emacs.d/straight/build/org/org-capture hides /usr/share/emacs/27.1/lisp/org/org-capture
/home/thibaut/.emacs.d/straight/build/org/ol-bbdb hides /usr/share/emacs/27.1/lisp/org/ol-bbdb
/home/thibaut/.emacs.d/straight/build/org/ob-makefile hides /usr/share/emacs/27.1/lisp/org/ob-makefile
/home/thibaut/.emacs.d/straight/build/org/ob-forth hides /usr/share/emacs/27.1/lisp/org/ob-forth
/home/thibaut/.emacs.d/straight/build/org/ob-comint hides /usr/share/emacs/27.1/lisp/org/ob-comint
/home/thibaut/.emacs.d/straight/build/org/ob-ref hides /usr/share/emacs/27.1/lisp/org/ob-ref
/home/thibaut/.emacs.d/straight/build/org/ob-eshell hides /usr/share/emacs/27.1/lisp/org/ob-eshell
/home/thibaut/.emacs.d/straight/build/org/ob-table hides /usr/share/emacs/27.1/lisp/org/ob-table
/home/thibaut/.emacs.d/straight/build/org/ob-mscgen hides /usr/share/emacs/27.1/lisp/org/ob-mscgen
/home/thibaut/.emacs.d/straight/build/org/ob-latex hides /usr/share/emacs/27.1/lisp/org/ob-latex
/home/thibaut/.emacs.d/straight/build/org/ox-publish hides /usr/share/emacs/27.1/lisp/org/ox-publish
/home/thibaut/.emacs.d/straight/build/org/org-datetree hides /usr/share/emacs/27.1/lisp/org/org-datetree
/home/thibaut/.emacs.d/straight/build/org/ob-hledger hides /usr/share/emacs/27.1/lisp/org/ob-hledger
/home/thibaut/.emacs.d/straight/build/org/org-clock hides /usr/share/emacs/27.1/lisp/org/org-clock
/home/thibaut/.emacs.d/straight/build/org/ob-ocaml hides /usr/share/emacs/27.1/lisp/org/ob-ocaml
/home/thibaut/.emacs.d/straight/build/org/ol-eww hides /usr/share/emacs/27.1/lisp/org/ol-eww
/home/thibaut/.emacs.d/straight/build/org/ob-sql hides /usr/share/emacs/27.1/lisp/org/ob-sql
/home/thibaut/.emacs.d/straight/build/org/org-tempo hides /usr/share/emacs/27.1/lisp/org/org-tempo
/home/thibaut/.emacs.d/straight/build/org/ob-processing hides /usr/share/emacs/27.1/lisp/org/ob-processing
/home/thibaut/.emacs.d/straight/build/org/ox-latex hides /usr/share/emacs/27.1/lisp/org/ox-latex
/home/thibaut/.emacs.d/straight/build/org/ox-icalendar hides /usr/share/emacs/27.1/lisp/org/ox-icalendar
/home/thibaut/.emacs.d/straight/build/org/ol-gnus hides /usr/share/emacs/27.1/lisp/org/ol-gnus
/home/thibaut/.emacs.d/straight/build/org/ob-abc hides /usr/share/emacs/27.1/lisp/org/ob-abc
/home/thibaut/.emacs.d/straight/build/org/ob-picolisp hides /usr/share/emacs/27.1/lisp/org/ob-picolisp
/home/thibaut/.emacs.d/straight/build/org/ob-fortran hides /usr/share/emacs/27.1/lisp/org/ob-fortran
/home/thibaut/.emacs.d/straight/build/org/ob-dot hides /usr/share/emacs/27.1/lisp/org/ob-dot
/home/thibaut/.emacs.d/straight/build/org/org-attach hides /usr/share/emacs/27.1/lisp/org/org-attach
/home/thibaut/.emacs.d/straight/build/org/ob-R hides /usr/share/emacs/27.1/lisp/org/ob-R
/home/thibaut/.emacs.d/straight/build/org/ob-emacs-lisp hides /usr/share/emacs/27.1/lisp/org/ob-emacs-lisp
/home/thibaut/.emacs.d/straight/build/org/ob-shell hides /usr/share/emacs/27.1/lisp/org/ob-shell
/home/thibaut/.emacs.d/straight/build/org/org-table hides /usr/share/emacs/27.1/lisp/org/org-table
/home/thibaut/.emacs.d/straight/build/org/org-colview hides /usr/share/emacs/27.1/lisp/org/org-colview
/home/thibaut/.emacs.d/straight/build/org/org-id hides /usr/share/emacs/27.1/lisp/org/org-id
/home/thibaut/.emacs.d/straight/build/org/ob-sed hides /usr/share/emacs/27.1/lisp/org/ob-sed
/home/thibaut/.emacs.d/straight/build/org/ob-eval hides /usr/share/emacs/27.1/lisp/org/ob-eval
/home/thibaut/.emacs.d/straight/build/org/org-agenda hides /usr/share/emacs/27.1/lisp/org/org-agenda
/home/thibaut/.emacs.d/straight/build/org/ol hides /usr/share/emacs/27.1/lisp/org/ol
/home/thibaut/.emacs.d/straight/build/org/org-entities hides /usr/share/emacs/27.1/lisp/org/org-entities
/home/thibaut/.emacs.d/straight/build/org/ob-sass hides /usr/share/emacs/27.1/lisp/org/ob-sass
/home/thibaut/.emacs.d/straight/build/org/ox-beamer hides /usr/share/emacs/27.1/lisp/org/ox-beamer
/home/thibaut/.emacs.d/straight/build/org/ob-matlab hides /usr/share/emacs/27.1/lisp/org/ob-matlab
/home/thibaut/.emacs.d/straight/build/org/ob-js hides /usr/share/emacs/27.1/lisp/org/ob-js
/home/thibaut/.emacs.d/straight/build/org/ol-mhe hides /usr/share/emacs/27.1/lisp/org/ol-mhe
/home/thibaut/.emacs.d/straight/build/org/ox-odt hides /usr/share/emacs/27.1/lisp/org/ox-odt
/home/thibaut/.emacs.d/straight/build/org/ob-sqlite hides /usr/share/emacs/27.1/lisp/org/ob-sqlite
/home/thibaut/.emacs.d/straight/build/org/ob-awk hides /usr/share/emacs/27.1/lisp/org/ob-awk
/home/thibaut/.emacs.d/straight/build/org/ol-w3m hides /usr/share/emacs/27.1/lisp/org/ol-w3m
/home/thibaut/.emacs.d/straight/build/org/ob hides /usr/share/emacs/27.1/lisp/org/ob
/home/thibaut/.emacs.d/straight/build/org/ob-io hides /usr/share/emacs/27.1/lisp/org/ob-io
/home/thibaut/.emacs.d/straight/build/org/ol-info hides /usr/share/emacs/27.1/lisp/org/ol-info
/home/thibaut/.emacs.d/straight/build/org/ox-html hides /usr/share/emacs/27.1/lisp/org/ox-html
/home/thibaut/.emacs.d/straight/build/org/ox hides /usr/share/emacs/27.1/lisp/org/ox
/home/thibaut/.emacs.d/straight/build/org/org-habit hides /usr/share/emacs/27.1/lisp/org/org-habit
/home/thibaut/.emacs.d/straight/build/org/ob-groovy hides /usr/share/emacs/27.1/lisp/org/ob-groovy
/home/thibaut/.emacs.d/straight/build/org/org-pcomplete hides /usr/share/emacs/27.1/lisp/org/org-pcomplete
/home/thibaut/.emacs.d/straight/build/org/org-faces hides /usr/share/emacs/27.1/lisp/org/org-faces
/home/thibaut/.emacs.d/straight/build/org/ob-org hides /usr/share/emacs/27.1/lisp/org/ob-org
/home/thibaut/.emacs.d/straight/build/org/ol-irc hides /usr/share/emacs/27.1/lisp/org/ol-irc
/home/thibaut/.emacs.d/straight/build/org/org-footnote hides /usr/share/emacs/27.1/lisp/org/org-footnote
/home/thibaut/.emacs.d/straight/build/org/ob-scheme hides /usr/share/emacs/27.1/lisp/org/ob-scheme
/home/thibaut/.emacs.d/straight/build/org/ox-org hides /usr/share/emacs/27.1/lisp/org/ox-org
/home/thibaut/.emacs.d/straight/build/org/org-timer hides /usr/share/emacs/27.1/lisp/org/org-timer
/home/thibaut/.emacs.d/straight/build/org/ol-eshell hides /usr/share/emacs/27.1/lisp/org/ol-eshell
/home/thibaut/.emacs.d/straight/build/org/ob-haskell hides /usr/share/emacs/27.1/lisp/org/ob-haskell
/home/thibaut/.emacs.d/straight/build/org/ol-rmail hides /usr/share/emacs/27.1/lisp/org/ol-rmail
/home/thibaut/.emacs.d/straight/build/org/ob-J hides /usr/share/emacs/27.1/lisp/org/ob-J
/home/thibaut/.emacs.d/straight/build/org/ob-java hides /usr/share/emacs/27.1/lisp/org/ob-java
/home/thibaut/.emacs.d/straight/build/org/ox-md hides /usr/share/emacs/27.1/lisp/org/ox-md
/home/thibaut/.emacs.d/straight/build/org/org-goto hides /usr/share/emacs/27.1/lisp/org/org-goto
/home/thibaut/.emacs.d/straight/build/org/org-indent hides /usr/share/emacs/27.1/lisp/org/org-indent
/home/thibaut/.emacs.d/straight/build/org/ob-tangle hides /usr/share/emacs/27.1/lisp/org/ob-tangle
/home/thibaut/.emacs.d/straight/build/org/ob-gnuplot hides /usr/share/emacs/27.1/lisp/org/ob-gnuplot
/home/thibaut/.emacs.d/straight/build/org/org-feed hides /usr/share/emacs/27.1/lisp/org/org-feed
/home/thibaut/.emacs.d/straight/build/org/ob-exp hides /usr/share/emacs/27.1/lisp/org/ob-exp
/home/thibaut/.emacs.d/straight/build/org/ob-coq hides /usr/share/emacs/27.1/lisp/org/ob-coq
/home/thibaut/.emacs.d/straight/build/org/ob-lilypond hides /usr/share/emacs/27.1/lisp/org/ob-lilypond
/home/thibaut/.emacs.d/straight/build/org/ob-lua hides /usr/share/emacs/27.1/lisp/org/ob-lua
/home/thibaut/.emacs.d/straight/build/org/ob-clojure hides /usr/share/emacs/27.1/lisp/org/ob-clojure
/home/thibaut/.emacs.d/straight/build/org/ob-ledger hides /usr/share/emacs/27.1/lisp/org/ob-ledger
/home/thibaut/.emacs.d/straight/build/org/ob-ruby hides /usr/share/emacs/27.1/lisp/org/ob-ruby
/home/thibaut/.emacs.d/straight/build/org/org-element hides /usr/share/emacs/27.1/lisp/org/org-element
/home/thibaut/.emacs.d/straight/build/org/ob-ditaa hides /usr/share/emacs/27.1/lisp/org/ob-ditaa
/home/thibaut/.emacs.d/straight/build/org/ox-texinfo hides /usr/share/emacs/27.1/lisp/org/ox-texinfo
/home/thibaut/.emacs.d/straight/build/org/org-inlinetask hides /usr/share/emacs/27.1/lisp/org/org-inlinetask
/home/thibaut/.emacs.d/straight/build/org/org-compat hides /usr/share/emacs/27.1/lisp/org/org-compat
/home/thibaut/.emacs.d/straight/build/org/org-macro hides /usr/share/emacs/27.1/lisp/org/org-macro
/home/thibaut/.emacs.d/straight/build/org/ob-calc hides /usr/share/emacs/27.1/lisp/org/ob-calc
/home/thibaut/.emacs.d/straight/build/org/ob-lisp hides /usr/share/emacs/27.1/lisp/org/ob-lisp
/home/thibaut/.emacs.d/straight/build/org/ob-octave hides /usr/share/emacs/27.1/lisp/org/ob-octave
/home/thibaut/.emacs.d/straight/build/org/ox-ascii hides /usr/share/emacs/27.1/lisp/org/ox-ascii
/home/thibaut/.emacs.d/straight/build/org/ob-core hides /usr/share/emacs/27.1/lisp/org/ob-core
/home/thibaut/.emacs.d/straight/build/org/ol-bibtex hides /usr/share/emacs/27.1/lisp/org/ol-bibtex
/home/thibaut/.emacs.d/straight/build/org/org-keys hides /usr/share/emacs/27.1/lisp/org/org-keys
/home/thibaut/.emacs.d/straight/build/org/org-src hides /usr/share/emacs/27.1/lisp/org/org-src
/home/thibaut/.emacs.d/straight/build/org/org-plot hides /usr/share/emacs/27.1/lisp/org/org-plot
/home/thibaut/.emacs.d/straight/build/org/ob-css hides /usr/share/emacs/27.1/lisp/org/ob-css
/home/thibaut/.emacs.d/straight/build/org/ox-man hides /usr/share/emacs/27.1/lisp/org/ox-man
/home/thibaut/.emacs.d/straight/build/org/ol-docview hides /usr/share/emacs/27.1/lisp/org/ol-docview
/home/thibaut/.emacs.d/straight/build/org/org-crypt hides /usr/share/emacs/27.1/lisp/org/org-crypt
/home/thibaut/.emacs.d/straight/build/org/org-mouse hides /usr/share/emacs/27.1/lisp/org/org-mouse
/home/thibaut/.emacs.d/straight/build/org/org-lint hides /usr/share/emacs/27.1/lisp/org/org-lint
/home/thibaut/.emacs.d/straight/build/org/org-mobile hides /usr/share/emacs/27.1/lisp/org/org-mobile
/home/thibaut/.emacs.d/straight/build/org/ob-maxima hides /usr/share/emacs/27.1/lisp/org/ob-maxima
/home/thibaut/.emacs.d/straight/build/org/ob-lob hides /usr/share/emacs/27.1/lisp/org/ob-lob
/home/thibaut/.emacs.d/straight/build/org/ob-ebnf hides /usr/share/emacs/27.1/lisp/org/ob-ebnf
/home/thibaut/.emacs.d/straight/build/org/ob-vala hides /usr/share/emacs/27.1/lisp/org/ob-vala
/home/thibaut/.emacs.d/straight/build/org/ob-shen hides /usr/share/emacs/27.1/lisp/org/ob-shen
/home/thibaut/.emacs.d/straight/build/org/ob-C hides /usr/share/emacs/27.1/lisp/org/ob-C
/home/thibaut/.emacs.d/straight/build/org/org-ctags hides /usr/share/emacs/27.1/lisp/org/org-ctags
/home/thibaut/.emacs.d/straight/build/org/org hides /usr/share/emacs/27.1/lisp/org/org
/home/thibaut/.emacs.d/straight/build/org/ob-perl hides /usr/share/emacs/27.1/lisp/org/ob-perl
/home/thibaut/.emacs.d/straight/build/org/org-attach-git hides /usr/share/emacs/27.1/lisp/org/org-attach-git
/home/thibaut/.emacs.d/straight/build/org/org-macs hides /usr/share/emacs/27.1/lisp/org/org-macs
/home/thibaut/.emacs.d/straight/build/org/org-num hides /usr/share/emacs/27.1/lisp/org/org-num
/home/thibaut/.emacs.d/straight/build/org/org-list hides /usr/share/emacs/27.1/lisp/org/org-list
/home/thibaut/.emacs.d/straight/build/org/org-install hides /usr/share/emacs/27.1/lisp/org/org-install
/home/thibaut/.emacs.d/straight/build/org/org-loaddefs hides /usr/share/emacs/27.1/lisp/org/org-loaddefs
/home/thibaut/.emacs.d/straight/build/org/ob-screen hides /usr/share/emacs/27.1/lisp/org/ob-screen
/home/thibaut/.emacs.d/straight/build/org/ob-plantuml hides /usr/share/emacs/27.1/lisp/org/ob-plantuml
/home/thibaut/.emacs.d/straight/build/let-alist/let-alist hides /usr/share/emacs/27.1/lisp/emacs-lisp/let-alist

Features:
(shadow sort mail-extr emacsbug sendmail ffap tramp tramp-loaddefs
trampver tramp-integration files-x tramp-compat ls-lisp windmove
make-mode vc-git diff-mode asm-mode tex-mode shell latexenc autorevert
filenotify pdf-tools package url-handlers pdf-view bookmark pp pdf-cache
pdf-info tq pdf-util cus-edit cus-start cus-load org-indent
org-superstar image-file org-tempo tempo ol-eww eww mm-url url-queue
ol-rmail ol-mhe ol-irc ol-info ol-gnus nnir gnus-sum url url-proxy
url-privacy url-expand url-methods url-history mailcap shr url-cookie
url-domsuf url-util url-parse auth-source json map url-vars svg xml dom
browse-url gnus-group gnus-undo gnus-start gnus-cloud nnimap nnmail
mail-source utf7 netrc nnoo parse-time iso8601 gnus-spec gnus-int
gnus-range message rmc puny rfc822 mml mml-sec password-cache epa
derived epg epg-config mm-decode mm-bodies mm-encode mail-parse rfc2231
mailabbrev gmm-utils mailheader gnus-win gnus nnheader gnus-util rmail
rmail-loaddefs rfc2047 rfc2045 ietf-drums text-property-search
mail-utils mm-util mail-prsvr wid-edit ol-docview doc-view jka-compr
image-mode exif ol-bibtex bibtex ol-bbdb ol-w3m rainbow-delimiters
pdf-tools-autoloads let-alist-autoloads tablist-autoloads
rainbow-delimiters-autoloads magit-autoloads git-commit-autoloads
with-editor-autoloads transient-autoloads async-autoloads
org-superstar-autoloads ob-mermaid ob-mermaid-autoloads ox-odt rng-loc
rng-uri rng-parse rng-match rng-dt rng-util rng-pttrn nxml-parse nxml-ns
nxml-enc xmltok nxml-util ox-latex ox-icalendar ox-html table ox-ascii
ox-publish ox org-element avl-tree generator org ob ob-tangle ob-ref
ob-lob ob-table ob-exp org-macro org-footnote org-src ob-comint
org-pcomplete pcomplete org-list org-faces org-entities time-date
noutline outline ob-emacs-lisp ob-core ob-eval org-table ol org-keys
org-compat org-macs org-loaddefs format-spec find-func cal-menu calendar
cal-loaddefs org-autoloads org-version face-remap auto-dim-other-buffers
auto-dim-other-buffers-autoloads doom-nord-theme pcase doom-themes
doom-themes-base doom-themes-autoloads perfect-margin-autoloads hl-line
paren display-line-numbers ace-window avy ace-window-autoloads
avy-autoloads vterm-autoloads perspective rx ido perspective-autoloads
counsel-projectile counsel-projectile-autoloads projectile grep ibuf-ext
ibuffer ibuffer-loaddefs thingatpt projectile-autoloads
pkg-info-autoloads epl-autoloads finder-inf helpful-autoloads
elisp-refs-autoloads f-autoloads dash-functional-autoloads
dash-autoloads use-package-bind-key which-key which-key-autoloads amx s
amx-autoloads s-autoloads ivy-rich ivy-rich-autoloads counsel xdg advice
xref project eieio eieio-core eieio-loaddefs dired dired-loaddefs
compile comint ansi-color swiper counsel-autoloads swiper-autoloads
diminish ivy delsel ring ivy-faces ivy-overlay colir color ivy-autoloads
use-package-diminish edmacro kmacro bind-key easy-mmode
diminish-autoloads cl-seq use-package-core use-package-autoloads
bind-key-autoloads straight-autoloads info cl-extra help-mode easymenu
seq byte-opt straight subr-x cl-macs gv cl-loaddefs cl-lib bytecomp
byte-compile cconv tooltip eldoc electric uniquify ediff-hook vc-hooks
lisp-float-type mwheel term/x-win x-win term/common-win x-dnd tool-bar
dnd fontset image regexp-opt fringe tabulated-list replace newcomment
text-mode elisp-mode lisp-mode prog-mode register page tab-bar menu-bar
rfn-eshadow isearch timer select scroll-bar mouse jit-lock font-lock
syntax facemenu font-core term/tty-colors frame minibuffer cl-generic
cham georgian utf-8-lang misc-lang vietnamese tibetan thai tai-viet lao
korean japanese eucjp-ms cp51932 hebrew greek romanian slovak czech
european ethiopic indian cyrillic chinese composite charscript charprop
case-table epa-hook jka-cmpr-hook help simple abbrev obarray
cl-preloaded nadvice loaddefs button faces cus-face macroexp files
text-properties overlay sha1 md5 base64 format env code-pages mule
custom widget hashtable-print-readable backquote threads dbusbind
inotify lcms2 dynamic-setting system-font-setting font-render-setting
cairo move-toolbar gtk x-toolkit x multi-tty make-network-process emacs)

Memory information:
((conses 16 390982 39498)
 (symbols 48 32321 2)
 (strings 32 110202 5273)
 (string-bytes 1 5030032)
 (vectors 16 52639)
 (vector-slots 8 916988 98920)
 (floats 8 818 314)
 (intervals 56 2108 0)
 (buffers 1000 61))
```

As for `auto-dim-other-buffers`'s configuration:
```
(use-package auto-dim-other-buffers
  :init
    (auto-dim-other-buffers-mode 1)
  :custom-face 
    (auto-dim-other-buffers-face ((t (:background "#2E3440")))) ; nord0
)
```
So not much is going on here.
my init.el is available here, in case something catches your eye there.
https://gitlab.com/titibandit/dotfiles/-/blob/master/private_dot_emacs.d/emacs.org

I would gladly give you more detailed information, but I'm not sure what could be directly of help :(
Thanks for the answer!

**Comment by mina86** [comment] 2021-02-10 17:26
OK, I see it with `pdf-view-mode`.

**Comment by mina86** [comment] 2021-02-10 18:52
https://github.com/politza/pdf-tools/pull/660

**Comment by mina86** [comment] 2021-02-10 18:57
This is a bug on pdf-tools side.  I’ve sent [a pull request](https://github.com/politza/pdf-tools/pull/660) with a fix though I dunno what’s their release cycle.  In the meantime, adding the following to `init.el` should do the trick:

    (eval-after-load "pdf-tools"
      (defun pdf-view-apply-hotspot-functions (window page image-size)
        (unless pdf-view-inhibit-hotspots
          (save-selected-window
            (when window (select-window window 'norecord))
            (apply 'nconc
                   (mapcar (lambda (fn)
                             (funcall fn page image-size))
                           (pdf-view-sorted-hotspot-functions)))))))

`'norecord` in the `select-window` call is the issue.

**Comment by titibandit** [comment] 2021-02-11 06:22
Thanks @mina86 ! 
The temporary fix indeed works :)
Let's see when your pull request gets merged now.

**Comment by vedang** [comment] 2021-02-20 07:46
Hello, I've merged the upstream change into `vedang/pdf-tools, thanks for submitting this PR!

**Comment by mina86** [comment] 2021-03-26 00:29
OK, I’m gonna go ahead and close this since this is now dependent on when pdf-tools gets new release.

**Closed by mina86** 2021-03-26 00:29 UTC
