### ISSUE TITLE
auto-dim doesn't work for find-file-other-window

### ISSUE THREAD

**Issue by tautologyclub** [mina86/auto-dim-other-buffers.el#17] opened 2018-06-08 08:48 UTC
Hey,

I use adob-mode all the time, but it doesn't handle some fringe cases well. Specifically find-file-other-window and similar functions. This is true even if I write something that manually triggers the adob--dim-buffer functions. I guess it's because there's some confusion about which window is currently focused when this occurs. Any ideas on how to resolve this?

**Comment by mina86** [comment] 2018-06-12 08:04
Could you provide reproduction steps? `M-x view-lossage RET` might help with that.

**Comment by tautologyclub** [comment] 2018-06-12 16:57
I can't reproduce any more. Weird.

**Comment by mina86** [comment] 2018-06-13 08:12
I cannot reproduce it either so closing for now. If this happens again `view-lossage` output might be helpful.

**Closed by mina86** 2018-06-13 08:12 UTC
