### ISSUE TITLE
Unfocused face when switching buffers

### ISSUE THREAD

**Issue by FlorentE96** [mina86/auto-dim-other-buffers.el#18] opened 2019-01-14 09:42 UTC
When switching buffers using C-x C-o, and even after navigating through the newly focused buffer, the unfocused face is still used.

**Comment by mina86** [comment] 2020-05-11 11:59
Does this still happen? I’ve pushed a few small improvements to the code in the meanwhile so perhaps version at HEAD works?

**Comment by mina86** [comment] 2020-05-18 11:08
I’m just pushed a fix for a different long-standing bug with the mode. Whatever the issue is here, that fix had chance to address it as well. As such, I’m going to close this report. Please reopen, if this can still be reproduced with newest ‘auto-dim-other-buffers’ and Emacs 27.1 or newer.

**Closed by mina86** 2020-05-18 11:08 UTC
